os : linux
dist: xenial
language : generic
jdk:
  - oraclejdk9

install: java -jar binaries/ssj.jar --build

# branch whitelist
branches:
  only:
  - master
  - gh-pages     # test the gh-pages branch
  - /pages-(.*)/ # test every branch which starts with "pages-"
  
deploy:
  provider: pages
  strategy: git
  repo: ashishdoneriya/ashishdoneriya.github.io
  target_branch: master
  cleanup: true
  token: $GITHUB_TOKEN
  local_dir: dist/
  on:
    branch: master
